services:
  db_postgres_students:
    image: postgres
    container_name: db_postgres_students
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env

  node_app_students:
    container_name: students
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_students
    env_file:
      - .env
